# Generated by Django 3.0.8 on 2020-07-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='subtitilo',
            new_name='subtitulo',
        ),
    ]
